### ISSUE TITLE
Bug compiling biblesync with clang

### ISSUE THREAD

**Issue by lsalvadore** [karlkleinpaste/biblesync#11]
I am working at creating a port of biblesync on FreeBSD, but I get an error in src/biblesync.cc at line 256 of the 2.0.1 release when using clang (default FreeBSD C compiler):
`if (bind(server_fd, (struct sockaddr*)&server,`
`			 sizeof(server)) == -1)`
`		{`
`		    ok_so_far = false;`
`		    retval += " bind";`
`		}`

The error is the following:
/usr/obj/usr/ports-poudriere/misc/biblesync/work/biblesync-2.0.1/src/biblesync.cc:257:32: error: invalid operands to binary expression ('__bind<int, sockaddr *, unsigned int>' and 'int')
                         (socklen_t)sizeof(server)) == -1)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~


The problem can be solved by using gcc, but if clang worked too it would be easier for FreeBSD users.

**Comment by karlkleinpaste** [comment]
i don't know what's going on here, but the code is plainly correct.
the "binary expression" is a "==" comparison.
bind(3) returns a signed int result. the result of bind() is being compared for equality against -1.
this looks to me like a clang error.

**Comment by ghost** [comment]
Thanks for looking into this.

I made a small search and found this:
https://stackoverflow.com/questions/39423474/socket-binding-wont-return-an-int

It suggests that the issue I reported can be solved by changing `bind` into `::bind`.
I just tried and it worked. It would be nice if it could be patched upstream (too bad it's too late for the 2.1.0 release).

**Comment by ghost** [comment]
I created a pull request to fix the issue (maybe it was not really necessary since it is really simple -- it just adds `::` --, but still you can merge it quicker).
