### ISSUE TITLE
There is an error in the 2.0.1 version

### ISSUE THREAD

**Issue by yetist** [karlkleinpaste/biblesync#9]
Please see here: https://github.com/karlkleinpaste/biblesync/blob/2.0.1/biblesync.pc.in#L12
1. Typing error, should be `biblesync`, but `bibleysnc`
2. Header file path error, more than one level biblesync directory.

Although [b16df42](https://github.com/karlkleinpaste/biblesync/commit/b16df4279c71791fb6a9c783be219d705801fd0b) has made repairs, tarball still has errors.

**Comment by alerque** [comment]
The tarball is still broken because a release has not been made since the fix. I realize it's minor, but broken is broken and if there are not any immediate prospects of further fixes that _have to_ make it in a patch release, I suggest a new minor release be made to fix this.
